### ISSUE TITLE
 'str' object has no attribute 'keys'

### ISSUE THREAD

**Issue by satyam1316** [Pierian-Data/Complete-Python-3-Bootcamp#176]
import json
n=int(input())
val=dict()
for n in range(n):
    val=input()
quarry=input()
print(quarry+"=")
if quarry in val.keys():
    print(val[quarry])
else:
    print("Not found")

By running this code it gives an error :-- 'str' object has no attribute 'keys'
so please solve this error

**Comment by walkershashi** [comment]
This is because you are taking direct input in the var inside the loop when you have already initialized the var to a dictionary before the loop.
Just after the line 5, var will become a string(as var = input() ), and hence loses its dict() functionality.

Hence the error arises.
Use any other value to make a key in var and then search for quarry.
