### ISSUE TITLE
Assessment test does not allow to click 'here' to enter answers

### ISSUE THREAD

**Issue by manvendrana** [Pierian-Data/Complete-Python-3-Bootcamp#233]
The assessment test does not allow to click 'here' to enter answers.

Tried opening in different browsers too but not able to make changes and take the test.

**Comment by Pierian-Data** [comment]
The notebooks here are always up and are visible for me, I just checked and can see the notebooks myself right now. Even if you have any issues viewing here on GitHub you can always **simply download the notebooks locally with the green button on the repo page as discussed and shown in the video lectures.** I am closing this issue since anyone can simply download the notebooks and run locally, if you are unsure about how to do that, please watch the setup and jupyter notebook lectures instead of posting an issue here, since it is not an issue with github or the notebooks. Also please keep  in mind we have answered this exact question multiple times already in the QA Forums on Udemy, so all you need to do is search the existing questions on the forums to quickly see the answers.
