### ISSUE TITLE
Test isn't displayed in my Github

### ISSUE THREAD

**Issue by hei-gui13** [Pierian-Data/Complete-Python-3-Bootcamp#239]
I can access the files for the Python Objects and Data Structures Assessment Test, but I can't see anything.
What's going on with the notebook?

**Comment by Harshit784** [comment]
I am facing the same issue

**Comment by CarolinaTC** [comment]
me too! i can't open any folder ...

**Comment by CarolinaTC** [comment]
if someone can help, i will be very grateful

**Comment by Pierian-Data** [comment]
Not sure what to say here? The notebooks here are always up and are visible for me, I just checked and can see the notebooks myself right now. Even if you have any issues viewing here on GitHub you can always **simply download the notebooks locally with the green button on the repo page as discussed and shown in the video lectures.** I am closing this issue since anyone can simply download the notebooks and run locally, if you are unsure about how to do that, please watch the setup and jupyter notebook lectures instead of posting an issue here, since it is not an issue with github or the notebooks. Also please keep  in mind we have answered this exact question multiple times already in the QA Forums on Udemy, so all you need to do is search the existing questions on the forums to quickly see the answers.
