### ISSUE TITLE
[Complete Python Bootcamp][ISSUE]- Can't access any content on git

### ISSUE THREAD

**Issue by CarolinaTC** [Pierian-Data/Complete-Python-3-Bootcamp#240]
Any content is being displayed on git. 
I can't access any content.
I attached an image of the current issue.
<img width="1440" alt="git_issue" src="https://user-images.githubusercontent.com/68920748/91433619-77ee5f00-e85b-11ea-8eab-0c47925d3970.png">

**Comment by Harshit784** [comment]
I'm having the same issue

**Comment by DannyS1982** [comment]
Same issues here

**Comment by Karishma1020** [comment]
I am facing the same problem

**Comment by allentsang24** [comment]
same here

**Comment by varupal** [comment]
same here

**Comment by shameer38in** [comment]
Same here. none of the files are opening

**Comment by Richlines** [comment]
Same issue- was working yesterday i think

**Comment by StuartDaniells** [comment]
Same issue here as well.
Am currently using the Jupiter notebook (Complete-Python-3-Bootcamp-master) notes to go through the course materials.

**Comment by JaiKapoor** [comment]
Yeah same issue

**Comment by Pierian-Data** [comment]
The notebooks here are always up and are visible for me, I just checked and can see the notebooks myself right now. Even if you have any issues viewing here on GitHub you can always **simply download the notebooks locally with the green button on the repo page as discussed and shown in the video lectures.** I am closing this issue since anyone can simply download the notebooks and run locally, if you are unsure about how to do that, please watch the setup and jupyter notebook lectures instead of posting an issue here, since it is not an issue with github or the notebooks. Also please keep  in mind we have answered this exact question multiple times already in the QA Forums on Udemy, so all you need to do is search the existing questions on the forums to quickly see the answers.
