### ISSUE TITLE
content is not visible 

### ISSUE THREAD

**Issue by RiteshPardeshi1** [Pierian-Data/Complete-Python-3-Bootcamp#246]
content is not visible...help

**Comment by atena5101** [comment]
content is not visible...help

در تاریخ پنجشنبه ۲۷ اوت ۲۰۲۰،‏ ۱۹:۵۸ RiteshPardeshi1 <
notifications@github.com> نوشت:

**Comment by Pierian-Data** [comment]
The notebooks here are always up and are visible for me, I just checked and can see the notebooks myself right now. Even if you have any issues viewing here on GitHub you can always **simply download the notebooks locally with the green button on the repo page as discussed and shown in the video lectures.** I am closing this issue since anyone can simply download the notebooks and run locally, if you are unsure about how to do that, please watch the setup and jupyter notebook lectures instead of posting an issue here, since it is not an issue with github or the notebooks. Also please keep  in mind we have answered this exact question multiple times already in the QA Forums on Udemy, so all you need to do is search the existing questions on the forums to quickly see the answers.
