### ISSUE TITLE
Not able to take the Data Structures assessment. 

### ISSUE THREAD

**Issue by KavyaT05** [Pierian-Data/Complete-Python-3-Bootcamp#321]
Hi, I am not able to take the Data Structures assessment. I am not able to answer or edit the cell.

**Comment by jefhar** [comment]
Which Jupyter Notebook are you using?

**Comment by KavyaT05** [comment]
Do you mean the version?

**Comment by jefhar** [comment]
The developer, name, and release of the Jupyter Notebook reader that you are using to access the files, and your operating system, version, and release date.

**Comment by KavyaT05** [comment]
Jupyter notebook - 6.1.4, Operating system- windows 10  Home Single
language 2020

**Comment by Pierian-Data** [comment]
the notebook files are still here, all you need to do is download them. If you are confused on what I mean by "download them", please re-watch the first few setup videos of the course, we walk through this entire process, if you are in the course, you should be viewing the notebooks locally, not here on github. Otherwise, you can't interact and type in them. Please review the videos, many students skip the first few set up videos which causes this confusion.

**Comment by KavyaT05** [comment]
Ok Thanks. Have a nice day.
