### ISSUE TITLE
notebook is not openeing

### ISSUE THREAD

**Issue by lambutang** [Pierian-Data/Complete-Python-3-Bootcamp#334]
its showing "something went wrong

**Comment by Brancog** [comment]
same for me!

**Comment by Pierian-Data** [comment]
Hello Everyone,

Nothing is "down", it just means GitHub is taking to long to show you its rendering of the notebook here, so it wont show it. But of course, the notebook files are still here, all you need to do is download them. If you are confused on what I mean by "download them", please re-watch the first few setup videos of the course, we walk through this entire process, if you are in the course, you should be viewing the notebooks locally, not here on github. Otherwise, you can't interact and type in them. Please review the videos, many students skip the first few set up videos which causes this confusion.
