### ISSUE TITLE
NOTEBOOK NOT OPENING

### ISSUE THREAD

**Issue by Jezan-Ufa** [Pierian-Data/Complete-Python-3-Bootcamp#335]
"Sorry, something went wrong" this is what it says.

**Comment by philipitaliano22** [comment]
Same thing it won't open for me

**Comment by a13aadhya** [comment]
same

**Comment by steliosdask** [comment]
Same problem here still

**Comment by GitKrzysztof** [comment]
same, Sorry, something went wrong. Reload?

**Comment by kilplixb23r** [comment]
I'm also have this issue

**Comment by YorayMauda** [comment]
Me too!! I hope someone will fix this issue soon.

**Comment by Pierian-Data** [comment]
All you need to do is download the notebooks, please review the videos, or
contact github support.

**Comment by ethaneum** [comment]
Still down

**Comment by Pierian-Data** [comment]
Hello Everyone,

Nothing is "down", it just means GitHub is taking to long to show you its rendering of the notebook here, so it wont show it. But of course, the notebook files are still here, all you need to do is download them. If you are confused on what I mean by "download them", please re-watch the first few setup videos of the course, we walk through this entire process, if you are in the course, you should be viewing the notebooks locally, not here on github. Otherwise, you can't interact and type in them. Please review the videos, many students skip the first few set up videos which causes this confusion.
