### ISSUE TITLE
where am i suppose to write my answering code in this assignment ?

### ISSUE THREAD

**Issue by Youngadams** [Pierian-Data/Complete-Python-3-Bootcamp#62]
[
![Screen Shot 2019-04-15 at 12 54 10 PM](https://user-images.githubusercontent.com/49657644/56161565-ae854b80-5f7e-11e9-889f-e044e97608d0.png)

**Comment by WahidaSahanazLaskar** [comment]
i m also facing same problem...couldnot able to write code under each question

**Comment by dhanushMindia** [comment]
What do you mean?

M Dhanush

**Comment by muqeeth08** [comment]
even i cant able to take any exam

**Comment by SquishyMuffins** [comment]
The fricken course person doesn't tell you how to actually take the fricken test.

**Comment by datttran** [comment]
lmao, if you guys need someone to teach you how to take the test, then maybe coding is not a good fit for you. It's really straight forward. There is nothing wrong with the test.
![image](https://user-images.githubusercontent.com/43898439/64914721-adae3c80-d70b-11e9-8aa0-d32692af7c42.png)

**Comment by Progammer1000** [comment]
Yeah it’s pretty straight forward!

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by baller-bry** [comment]
I was also confused at first on how to write my answers, but I figured it out. You have to download the files for the course, then upload the test assessment in a jupyter notebook! You don't have to submit it because it's for your own personal review. The next lesson will then be the solutions to the questions.
