### ISSUE TITLE
my function returns only string from a list,why is the list not mapping with the function.

### ISSUE THREAD

**Issue by neversaymyname** [Pierian-Data/Complete-Python-3-Bootcamp#63]
def e_e(listing):
    d=[]
    for a in listing:
        if type(a)==str:
            d.append(a)
        else:
            False
    return d

my_list=['dragon',1,'ball',2,'zzz']
list(map(e_e,my_list))

**Comment by carlcx52a** [comment]
Hi there, I don't know your name so I'm not gonna say it. 

The reason is you're using 'map', so it takes every item in 'my_list' and puts in your function to do the loop as below:

e_e('dragon')
e_e(1)
e_e('ball')
e_e(2)
e_e('zzz')

However, the integers 1 and 2 are not iterable so it throws out the error. Instead of using 'map', you can just do print(e_e(my_list)) and you will get all strings from your list. Hope this helps.

**Comment by neversaymyname** [comment]
Hi thanks a lot for not saying my name.
can you let me know then why integers are iterating in this then -
def sq_n(num):
    return num**num
l=[1,2,3,4]
list(map(sq_n,l))

#output=[1,4,9,16]

**Comment by neversaymyname** [comment]
as much as i am understanding is this because map is already iterating them and i cannot use one more for loop within for intergers?
