### ISSUE TITLE
'str' object has no attribute 'keys' while accessing Dictionary 

### ISSUE THREAD

**Issue by Hyde1512** [Pierian-Data/Complete-Python-3-Bootcamp#85]
##ini_dict = {'NYC': ['10.00', '5.00', '2.00'], 'SFO': ['12.00', '4.00', '2.00']}  -- Initial dictionary 
 code to sum the value of each key in dictionary 
result = {} 
for d in ini_dict: 
    for k in d.keys():  --> Error str' object has no attribute 'keys'
        result[k] = result.get(k, 0) + d[k]

**Comment by thien023456** [comment]
Hi, i ran this code. As i know, after run the first for loop, the result of d is a [NYC] and [SFO] and those result are the List with string value, and the string object has not a dictionary, so when you run the second for loop it will be error because d isn't a dictionary. Hope it help you.
Btw, this is my solution for sum the value of each key in dictionary 
```
new_dict = {}
for key,value in ini_dict.items():
    value = [int(float(x)) for x in value]
    sum_values = sum(value)
    new_dict[key] = sum_values
print(new_dict)
```
